name: Ubuntu

on:

  # On any push or pull_request request for ubuntu
  push:
  pull_request:

  # Automated test every monday
  schedule:
      - cron: '0 13 * * 1' 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.10.2]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install pytest
        pip install .
    - name: Run py tests
      run: |
        pytest